# spring.application.name=ecommerce
spring:
  application:
    name: ecommerce

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:yourpassword}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} 
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email, read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  security:
    jwt:
      secret-key: ${JWT_SECRET} # 256-bit key على الأقل
      access-token-expiration: 900000 # 15 دقيقة بالـ ms
      refresh-token-expiration: 604800000 # 7 أيام بالـ ms
    verification:
      token-expiry-hours: 24
    reset:
      token-expiry-hours: 1
    lockout:
      max-attempts: 5
      duration-minutes: 30

# Actuator endpoints للـ health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
